name: 'App Token'
description: 'Get GitHub App token'
inputs:
  app-id:
    description: "GitHub App ID"
    required: true
  private-key:
    description: "GitHub App private key"
    required: true
outputs:
  token:
    description: "GitHub installation access token"
    value: ${{ steps.app-token.outputs.token }}
  installation-id:
    description: "GitHub App installation ID"
    value: ${{ steps.app-token.outputs.installation-id }}
  app-slug:
    description: "GitHub App slug"
    value: ${{ steps.app-token.outputs.app-slug }}
  user-name:
    description: "GitHub App User Name"
    value: ${{ steps.app-user.outputs.user-name }}
  user-email:
    description: "GitHub App User Email"
    value: ${{ steps.app-user.outputs.user-email }}
  user-id:
    description: "GitHub App User ID"
    value: ${{ steps.app-user.outputs.user-id }}
  committer:
    description: "GitHub App Committer String"
    value: ${{ steps.app-user.outputs.committer }}
runs:
  using: "composite"
  steps:
    - uses: actions/create-github-app-token@v1.11.0
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
    - name: Get GitHub App User ID
      id: app-user
      shell: bash
      run: |
        USER_NAME="${{ steps.app-token.outputs.app-slug }}[bot]"
        USER_ID="$(gh api "/users/$USER_NAME" --jq .id)"
        USER_EMAIL="${USER_ID}+${USER_NAME}@users.noreply.github.com"
        echo "user-id=$USER_ID" >> "$GITHUB_OUTPUT"
        echo "user-name=$USER_NAME" >> "$GITHUB_OUTPUT"
        echo "user-email=$USER_EMAIL" >> "$GITHUB_OUTPUT"
        echo "committer=$USER_NAME <$USER_EMAIL>" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
