name: 'Transition Jira Issue'
description: 'Transition Jira Issue'
inputs:
  token:
    description: "Token to connect to Jira"
    required: true
  issue-key:
    description: "Issue Key"
    required: true
  transition-id:
    description: "Id of Transition"
    required: true
  resolution:
    description: "Resolution of Transition"
runs:
  using: "composite"
  steps:
    - id: find
      shell: bash
      env:
        JIRA_API_TOKEN: ${{ inputs.token }}
        ISSUE_KEY: ${{ inputs.issue-key }}
        TRANSITION_ID: ${{ inputs.transition-id }}
        RESOLUTION: ${{ inputs.resolution }}
      run: |
        request=$(jq -n --arg transition_id "$TRANSITION_ID" '{"transition":{"id":$transition_id}}')
        if [[ -n "$RESOLUTION" ]]; then
          request=$(echo $request | jq --arg resolution "$RESOLUTION" '[.,{fields:{resolution:{name:$resolution}}}] | add')
        fi
        echo "REQUEST=${request}"
        json_response=$(curl --fail --request POST \
          --url "https://jira.mongodb.org/rest/api/2/issue/$ISSUE_KEY/transitions" \
          --header 'Authorization: Bearer '"${JIRA_API_TOKEN}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data "$request")
        echo "RESPONSE=${json_response}"
