name: 'Comment Jira Issue'
description: 'Comment Jira Issue'
inputs:
  token:
    description: "Token to connect to Jira"
    required: true
  issue-key:
    description: "Issue Key"
    required: true
  comment:
    description: "Comment to add to the issue"
    required: true
  api-base:
    description: "Base URL for the Jira API"
    default: "https://jira.mongodb.org"
runs:
  using: "composite"
  steps:
    - id: find
      shell: bash
      env:
        JIRA_API_BASE: ${{ inputs.api-base }}
        JIRA_API_TOKEN: ${{ inputs.token }}
        ISSUE_KEY: ${{ inputs.issue-key }}
        COMMENT: ${{ inputs.comment }}
      run: |
        request=$(jq -n --arg comment "$COMMENT" '{"body":$comment}')
        echo "Request: $request"
        json_response=$(curl --fail --request POST \
          --url "${JIRA_API_BASE}/rest/api/2/issue/$ISSUE_KEY/comment" \
          --header 'Authorization: Bearer '"${JIRA_API_TOKEN}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data "$request")
