name: 'Comment Jira Issue'
description: 'Comment Jira Issue'
inputs:
  token:
    description: "Token to connect to Jira"
    required: true
  issue-key:
    description: "Issue Key"
    required: true
  comment:
    description: "Comment to add to the issue"
    required: true
  api-base:
    description: "Base URL for the Jira API"
    default: "https://jira.mongodb.org"
runs:
  using: "node20"
  main: "dist/index.js"
