use std::{
    path::Path,
    time::{SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result};
use git2::{
    Cred, IndexAddOption, PushOptions, RemoteCallbacks, Repository, Signature, StatusOptions,
};
use octocrab::{Octocrab, models::IssueState, params};
use redacted::FullyRedacted;
use tracing::info;

use crate::shared::{GithubToken, Repo};

const LABEL: &str = "apix-action";
const TITLE: &str = "ci: apix-action updates";

/// Close old generated PRs, publish changes, and open replacement PRs.
pub async fn create(
    repositories: Vec<Repo>,
    targets: impl AsRef<Path>,
    token: FullyRedacted<GithubToken>,
) -> Result<()> {
    let github = Octocrab::builder()
        .personal_token(token.expose_secret())
        .build()
        .context("creating GitHub client")?;

    // Close open PRs carrying `apix-action` before opening replacement PRs.
    for repository in &repositories {
        close_labeled_pull_requests(&github, repository).await?;
    }

    // One unique branch name is reused across target repositories.
    let branch = format!(
        "ci/api-action-{}",
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .context("reading system clock")?
            .as_nanos()
    );

    for repository in repositories {
        let path = targets
            .as_ref()
            .join(repository.owner.as_str())
            .join(repository.repository.as_str());
        let actions = changed_workflows(&path).with_context(|| {
            format!(
                "finding changed workflows for {}/{}",
                repository.owner, repository.repository
            )
        })?;
        let base = publish_changes(&path, &branch, &token).with_context(|| {
            format!(
                "publishing changes for {}/{}",
                repository.owner, repository.repository
            )
        })?;

        let pull_request = github
            .pulls(repository.owner.as_str(), repository.repository.as_str())
            .create(TITLE, format!("{}:{branch}", repository.owner), &base)
            .body(description(&actions))
            .send()
            .await
            .with_context(|| {
                format!(
                    "creating pull request for {}/{}",
                    repository.owner, repository.repository
                )
            })?;

        github
            .issues(repository.owner.as_str(), repository.repository.as_str())
            .add_labels(pull_request.number, &[LABEL.to_string()])
            .await
            .with_context(|| {
                format!(
                    "labeling pull request for {}/{}",
                    repository.owner, repository.repository
                )
            })?;
        info!(url = %format_args!("https://github.com/{}/{}/pull/{}", repository.owner, repository.repository, pull_request.number), "pull request created");
    }

    Ok(())
}

// Read statuses before publish_changes commits them.
fn changed_workflows(path: &Path) -> Result<Vec<String>> {
    let repository = Repository::open(path).context("opening repository")?;
    let mut options = StatusOptions::new();
    options
        .include_untracked(true)
        .recurse_untracked_dirs(true)
        .exclude_submodules(true);

    let statuses = repository.statuses(Some(&mut options))?;
    let mut actions = Vec::new();
    for status in statuses.iter() {
        let path = status.path().context("reading changed path")?;
        if let Some(path) = path.strip_prefix(".github/workflows/") {
            actions.push(path.to_owned());
        }
    }
    actions.sort();
    actions.dedup();
    Ok(actions)
}

// Build the Markdown body listing workflows changed for one repository.
fn description(actions: &[String]) -> String {
    let actions = actions
        .iter()
        .map(|action| format!("- `{action}`"))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "## 🤖 Automated sync\n\nThis pull request was autogenerated to sync this repository from `api-actions`.\n\n## Actions changed\n\n{actions}"
    )
}

// Close open pull requests carrying the `apix-action` label.
async fn close_labeled_pull_requests(github: &Octocrab, repository: &Repo) -> Result<()> {
    let pulls = github
        .pulls(repository.owner.as_str(), repository.repository.as_str())
        .list()
        .state(params::State::Open)
        .per_page(100)
        .send()
        .await
        .with_context(|| {
            format!(
                "listing pull requests in {}/{}",
                repository.owner, repository.repository
            )
        })?;
    let pulls = github.all_pages(pulls).await?;

    for pull_request in pulls {
        let has_label = pull_request
            .labels
            .as_deref()
            .unwrap_or_default()
            .iter()
            .any(|label| label.name == LABEL);
        if !has_label {
            continue;
        }

        github
            .issues(repository.owner.as_str(), repository.repository.as_str())
            .update(pull_request.number)
            .state(IssueState::Closed)
            .send()
            .await
            .with_context(|| format!("closing pull request #{}", pull_request.number))?;
        info!(url = %format_args!("https://github.com/{}/{}/pull/{}", repository.owner, repository.repository, pull_request.number), "pull request closed");
    }

    Ok(())
}

// Commit current generated files on a branch and push it to origin.
fn publish_changes(
    path: &Path,
    branch: &str,
    token: &FullyRedacted<GithubToken>,
) -> Result<String> {
    let repository = Repository::open(path).context("opening repository")?;
    let base = repository
        .head()
        .context("reading repository HEAD")?
        .shorthand()
        .context("repository has detached HEAD")?
        .to_owned();
    let commit = repository
        .head()
        .context("reading repository HEAD")?
        .peel_to_commit()
        .context("resolving repository HEAD")?;

    // Commit generated files on a fresh branch, then push it for the PR.
    repository.branch(branch, &commit, false)?;
    repository.set_head(&format!("refs/heads/{branch}"))?;
    repository.checkout_head(None)?;

    let mut index = repository.index()?;
    index.add_all(["*"], IndexAddOption::DEFAULT, None)?;
    index.write()?;
    let tree = repository.find_tree(index.write_tree()?)?;
    let signature = Signature::now("apix-action", "apix-action@mongodb.com")?;
    repository.commit(
        Some("HEAD"),
        &signature,
        &signature,
        TITLE,
        &tree,
        &[&commit],
    )?;

    let mut callbacks = RemoteCallbacks::new();
    callbacks
        .credentials(|_, _, _| Cred::userpass_plaintext("x-access-token", token.expose_secret()));
    callbacks.push_update_reference(|reference, status| {
        status.map_or(Ok(()), |status| {
            Err(git2::Error::from_str(&format!(
                "GitHub rejected push for {reference}: {status}"
            )))
        })
    });
    let mut options = PushOptions::new();
    options.remote_callbacks(callbacks);
    repository.find_remote("origin")?.push(
        &[format!("refs/heads/{branch}:refs/heads/{branch}")],
        Some(&mut options),
    )?;

    Ok(base)
}

#[cfg(test)]
mod tests {
    use std::{fs, time::SystemTime};

    use anyhow::Result;

    use super::{changed_workflows, description};

    #[test]
    fn description_lists_changed_actions() {
        let actions = vec!["dependabot-auto-merge.yaml".to_string()];
        assert_eq!(
            description(&actions),
            "## 🤖 Automated sync\n\nThis pull request was autogenerated to sync this repository from `api-actions`.\n\n## Actions changed\n\n- `dependabot-auto-merge.yaml`"
        );
    }

    #[test]
    fn changed_workflows_excludes_other_changed_files() -> Result<()> {
        let unique = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)?
            .as_nanos();
        let root = std::env::temp_dir().join(format!("apix-prs-{}-{unique}", std::process::id()));
        let workflows = root.join(".github/workflows");
        fs::create_dir_all(&workflows)?;
        fs::write(workflows.join("dependabot-auto-merge.yaml"), "workflow")?;
        fs::write(root.join("README.md"), "readme")?;
        git2::Repository::init(&root)?;

        assert_eq!(
            changed_workflows(&root)?,
            vec!["dependabot-auto-merge.yaml"]
        );

        fs::remove_dir_all(root)?;
        Ok(())
    }
}
