use std::{
    path::Path,
    time::{SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result};
use git2::{Cred, IndexAddOption, PushOptions, RemoteCallbacks, Repository, Signature};
use octocrab::{Octocrab, models::IssueState, params};
use redacted::FullyRedacted;
use tracing::info;

use crate::shared::{GithubToken, Repo, SyncWorkflow};

const LABEL: &str = "apix-action";
const TITLE: &str = "ci: apix-action updates";

pub async fn create(
    workflows: &[SyncWorkflow],
    repositories: Vec<Repo>,
    targets: impl AsRef<Path>,
    token: FullyRedacted<GithubToken>,
) -> Result<()> {
    let github = Octocrab::builder()
        .personal_token(token.expose_secret())
        .build()
        .context("creating GitHub client")?;

    for repository in &repositories {
        close_labeled_pull_requests(&github, repository).await?;
    }

    let branch = format!(
        "ci/api-action-{}",
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .context("reading system clock")?
            .as_nanos()
    );

    for repository in repositories {
        let path = targets
            .as_ref()
            .join(repository.owner.as_str())
            .join(repository.repository.as_str());
        let base = publish_changes(&path, &branch, &token).with_context(|| {
            format!(
                "publishing changes for {}/{}",
                repository.owner, repository.repository
            )
        })?;

        let pull_request = github
            .pulls(repository.owner.as_str(), repository.repository.as_str())
            .create(TITLE, format!("{}:{branch}", repository.owner), &base)
            .body(description(workflows, &repository))
            .send()
            .await
            .with_context(|| {
                format!(
                    "creating pull request for {}/{}",
                    repository.owner, repository.repository
                )
            })?;

        github
            .issues(repository.owner.as_str(), repository.repository.as_str())
            .add_labels(pull_request.number, &[LABEL.to_string()])
            .await
            .with_context(|| {
                format!(
                    "labeling pull request for {}/{}",
                    repository.owner, repository.repository
                )
            })?;
        info!(url = %format_args!("https://github.com/{}/{}/pull/{}", repository.owner, repository.repository, pull_request.number), "pull request created");
    }

    Ok(())
}

fn description(workflows: &[SyncWorkflow], repository: &Repo) -> String {
    let mut actions: Vec<_> = workflows
        .iter()
        .filter(|workflow| workflow.sync.contains(repository))
        .map(|workflow| workflow.file_name.to_string_lossy().into_owned())
        .collect();
    actions.sort();
    actions.dedup();

    let actions = actions
        .into_iter()
        .map(|action| format!("- `{action}`"))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "## 🤖 Automated sync\n\nThis pull request was autogenerated to sync this repository from `api-actions`.\n\n## Actions changed\n\n{actions}"
    )
}

async fn close_labeled_pull_requests(github: &Octocrab, repository: &Repo) -> Result<()> {
    let pulls = github
        .pulls(repository.owner.as_str(), repository.repository.as_str())
        .list()
        .state(params::State::Open)
        .per_page(100)
        .send()
        .await
        .with_context(|| {
            format!(
                "listing pull requests in {}/{}",
                repository.owner, repository.repository
            )
        })?;
    let pulls = github.all_pages(pulls).await?;

    for pull_request in pulls {
        let has_label = pull_request
            .labels
            .as_deref()
            .unwrap_or_default()
            .iter()
            .any(|label| label.name == LABEL);
        if !has_label {
            continue;
        }

        github
            .issues(repository.owner.as_str(), repository.repository.as_str())
            .update(pull_request.number)
            .state(IssueState::Closed)
            .send()
            .await
            .with_context(|| format!("closing pull request #{}", pull_request.number))?;
        info!(url = %format_args!("https://github.com/{}/{}/pull/{}", repository.owner, repository.repository, pull_request.number), "pull request closed");
    }

    Ok(())
}

fn publish_changes(
    path: &Path,
    branch: &str,
    token: &FullyRedacted<GithubToken>,
) -> Result<String> {
    let repository = Repository::open(path).context("opening repository")?;
    let base = repository
        .head()
        .context("reading repository HEAD")?
        .shorthand()
        .context("repository has detached HEAD")?
        .to_owned();
    let commit = repository
        .head()
        .context("reading repository HEAD")?
        .peel_to_commit()
        .context("resolving repository HEAD")?;

    repository.branch(branch, &commit, false)?;
    repository.set_head(&format!("refs/heads/{branch}"))?;
    repository.checkout_head(None)?;

    let mut index = repository.index()?;
    index.add_all(["*"], IndexAddOption::DEFAULT, None)?;
    index.write()?;
    let tree = repository.find_tree(index.write_tree()?)?;
    let signature = Signature::now("apix-action", "apix-action@mongodb.com")?;
    repository.commit(
        Some("HEAD"),
        &signature,
        &signature,
        TITLE,
        &tree,
        &[&commit],
    )?;

    let mut callbacks = RemoteCallbacks::new();
    callbacks
        .credentials(|_, _, _| Cred::userpass_plaintext("x-access-token", token.expose_secret()));
    callbacks.push_update_reference(|reference, status| {
        status.map_or(Ok(()), |status| {
            Err(git2::Error::from_str(&format!(
                "GitHub rejected push for {reference}: {status}"
            )))
        })
    });
    let mut options = PushOptions::new();
    options.remote_callbacks(callbacks);
    repository.find_remote("origin")?.push(
        &[format!("refs/heads/{branch}:refs/heads/{branch}")],
        Some(&mut options),
    )?;

    Ok(base)
}

#[cfg(test)]
mod tests {
    use std::ffi::OsString;

    use non_empty_string::NonEmptyString;

    use super::description;
    use crate::shared::{Repo, SyncWorkflow};

    #[test]
    fn description_lists_actions_for_repository() {
        let repository = Repo::new(
            // Safe: test literals are non-empty.
            NonEmptyString::new("owner".to_string()).expect("non-empty owner"),
            // Safe: test literals are non-empty.
            NonEmptyString::new("repository".to_string()).expect("non-empty repository"),
        );
        let workflows = vec![
            SyncWorkflow {
                file_name: OsString::from("z.yaml"),
                sync: vec![repository.clone()],
                contents: String::new(),
            },
            SyncWorkflow {
                file_name: OsString::from("a.yaml"),
                sync: vec![repository.clone()],
                contents: String::new(),
            },
        ];

        assert_eq!(
            description(&workflows, &repository),
            "## 🤖 Automated sync\n\nThis pull request was autogenerated to sync this repository from `api-actions`.\n\n## Actions changed\n\n- `a.yaml`\n- `z.yaml`"
        );
    }
}
