name: Auto Close Jira (reusable)

on:
  workflow_call:

permissions:
  pull-requests: read
  contents: read

jobs:
  close-jira:
    name: Close Jira ticket
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: 1password/load-secrets-action@v4
        id: load-secrets
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          JIRA_API_TOKEN: "op://APIx/JIRA service account/credential"
      - name: Determine transition
        id: transition
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "id=1381" >> "$GITHUB_OUTPUT"
            echo "resolution=Fixed" >> "$GITHUB_OUTPUT"
          else
            echo "id=1371" >> "$GITHUB_OUTPUT"
            echo "resolution=Won't Fix" >> "$GITHUB_OUTPUT"
          fi
      - name: Find Jira key
        id: find
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          JIRA_KEY=$(gh pr view "$URL" --comments | grep 'was created for internal tracking' | grep -oE 'CLOUDP-[0-9]+' | head -1)
          echo "key=$JIRA_KEY" >> "$GITHUB_OUTPUT"
      - name: Transition Jira ticket
        uses: mongodb/apix-action/transition-jira@v14
        with:
          token: ${{ steps.load-secrets.outputs.JIRA_API_TOKEN }}
          issue-key: ${{ steps.find.outputs.key }}
          transition-id: ${{ steps.transition.outputs.id }}
          resolution: ${{ steps.transition.outputs.resolution }}
