name: Create Jira Ticket for Dependabot PRs (reusable)

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read

jobs:
  create-jira:
    name: Create Jira ticket
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: 1password/load-secrets-action@v4
        id: load-secrets
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          JIRA_API_TOKEN: "op://APIx/JIRA service account/credential"
      - name: Determine repo config
        id: config
        run: |
          case "${{ github.repository }}" in
            */atlas-local-lib|*/atlas-local-cli|*/atlas-local-lib-js)
              echo "component=local-atlas-experience" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "component=AtlasCLI" >> "$GITHUB_OUTPUT"
              ;;
          esac
      - name: Create Jira ticket
        uses: mongodb/apix-action/create-jira@v14
        id: create
        with:
          token: ${{ steps.load-secrets.outputs.JIRA_API_TOKEN }}
          project-key: CLOUDP
          summary: "[${{ github.event.repository.name }}] ${{ github.event.pull_request.title }}"
          issuetype: Story
          description: "This ticket tracks the following GitHub pull request: ${{ github.event.pull_request.html_url }}"
          components: ${{ steps.config.outputs.component }}
          assignee: cloud-atlascli-escalation
          extra-data: |
            {
              "fields": {
                "fixVersions": [{"name": "Not Applicable"}],
                "customfield_12751": [{"id": "22223"}],
                "customfield_10257": {"id": "11861"}
              }
            }
      - name: Add comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The ticket [${{ steps.create.outputs.issue-key }}](https://jira.mongodb.org/browse/${{ steps.create.outputs.issue-key }}) was created for internal tracking.

            Note: Jira ticket will be closed automatically when this PR is merged.
      - name: Add auto_close_jira label
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "auto_close_jira"
