name: Auto merge dependabot prs

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-merge:
    name: Auto merge dependabot prs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}
    - name: Set Apix Bot token
      id: app-token
      uses: mongodb/apix-action/token@222db38e5893a57f26bd156999713aa98a55b92c
      with:
        app-id: ${{ secrets.APIXBOT_APP_ID }}
        private-key: ${{ secrets.APIXBOT_APP_PEM }}
    - name: Auto merge PR
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        gh pr merge "${{ github.event.pull_request.html_url }}" --auto --squash
