# sync -> mongodb/mongodb-atlas-local
# sync -> mongodb/atlas-local-lib
# sync -> mongodb/atlas-local-cli
# sync -> mongodb-js/atlas-local-lib-js
# sync -> mongodb/atlas-local-lib-py
# sync -> mongodb-labs/cobra2snooty

name: Reopen Jira Ticket on Issue Reopen

on:
  issues:
    types: [reopened]

permissions: {}

jobs:
  reopen-jira:
    permissions:
      contents: read
      issues: read
    uses: mongodb/apix-action/.github/workflows/_issue-reopened.yaml@8c5007247643059c0d15c061290a345eb987657f # main
    secrets: inherit
