# sync -> mongodb/mongodb-atlas-local
# sync -> mongodb/atlas-local-lib
# sync -> mongodb/atlas-local-cli
# sync -> mongodb-js/atlas-local-lib-js
# sync -> mongodb/atlas-local-lib-py
# sync -> mongodb-labs/cobra2snooty

name: Close Jira Ticket on Issue Close

on:
  issues:
    types: [closed]

permissions: {}

jobs:
  close-jira:
    permissions:
      contents: read
      issues: read
    uses: mongodb/apix-action/.github/workflows/_issue-closed.yaml@de4ebdef39f1941757616df20a791cbd4698aa0c # main
    secrets: inherit
